-- Core configs
require "user.keymaps"
require "user.plugins"
require "user.options"
require "user.autocommands"
require "user.functions"

-- Plugin configs
require "user.alpha"
require "user.bufferline"
-- require "user.colorizer"
require "user.colorscheme"
require "user.git-blame"
require "user.gitsigns"
require "user.icons"
require "user.lualine"
require "user.nvim-tree"
require "user.telescope-file-browser"
require "user.toggleterm"
require "user.telescope"
require "user.whichkey"
require "user.lsp"

-- require "user.treesitter"
require "user.surround"
require "user.notify"
require "user.colorizer"
-- require "user.registers"
require "user.nvim-webdev-icons"
require "user.dap"
require "user.indentline"
require "user.comment"
require "user.autopairs"
require "user.numb"
require "user.matchup"
require "user.neoscroll"
require "user.vim-slash"
require "user.cmp"
